# Dockerfile.ansible_agent
FROM ubuntu:22.04

# Отключаем интерактивные вопросы при установке
ENV DEBIAN_FRONTEND=noninteractive

# Устанавливаем зависимости и Ansible
RUN apt-get update && apt-get install -y \
    ansible \
    openssh-client \
    git \
    python3 \
    sudo \
 && rm -rf /var/lib/apt/lists/*

# Создаем пользователя ansible
RUN useradd -ms /bin/bash ansible && echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Рабочая директория
WORKDIR /home/ansible

# Команда, чтобы контейнер оставался запущенным
CMD ["tail", "-f", "/dev/null"]
