FROM ubuntu:22.04

RUN apt-get update && apt-get install -y openssh-server sudo \
    && mkdir /var/run/sshd \
    && useradd -m -s /bin/bash ansible \
    && echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]
